DOMAIN = "adaptive_irrigation"

CONF_WEATHER_ENTITY = "weather_entity"
DEFAULT_WEATHER_ENTITY = "weather.home"

CONF_ZONE_NAME = "zone_name"
CONF_ZONE_TYPE = "zone_type"
CONF_VALVE_SWITCH = "valve_switch"
CONF_SOIL_SENSORS = "soil_sensors"
CONF_MOTION_SENSOR = "motion_sensor"
CONF_SOIL_THRESHOLD = "soil_threshold"
CONF_MAX_DURATION = "max_duration"
CONF_FALLBACK_DURATION = "fallback_duration"
CONF_CROP_COEFFICIENT = "crop_coefficient"
CONF_SENSOR_REQUIRED = "sensor_required"
CONF_MIN_INTERVAL = "min_interval"
CONF_WATER_INTERVAL_DAYS = "water_interval_days"
CONF_WINDOW_START_HOUR = "window_start_hour"
CONF_WINDOW_END_HOUR = "window_end_hour"
CONF_WATER_METER_ENTITY = "water_meter_entity"
CONF_DAILY_BUDGET_GALLONS = "daily_budget_gallons"
CONF_FLOW_RATE_GPM = "flow_rate_gpm"

ZONE_TYPE_SUMMER = "summer"
ZONE_TYPE_SEEDLING = "seedling"
DEFAULT_ZONE_TYPE = ZONE_TYPE_SUMMER

SEEDLING_DEFAULT_THRESHOLD = 35
SEEDLING_DEFAULT_FALLBACK = 4

DEFAULT_WATER_INTERVAL_DAYS = 3
DEFAULT_WINDOW_START_HOUR = 5
DEFAULT_WINDOW_END_HOUR = 10
DEFAULT_FLOW_RATE_GPM = 2.0
DEFAULT_DAILY_BUDGET_GALLONS = 0.0
PEER_TREND_DRYING_THRESHOLD = -0.3  # %/hr — peers drying this fast triggers early watering

DEFAULT_SOIL_THRESHOLD = 25
DEFAULT_MAX_DURATION = 20
DEFAULT_FALLBACK_DURATION = 6
DEFAULT_MIN_INTERVAL = 45
DEFAULT_CROP_COEFFICIENT = "0.8"

CONF_SOAK_CYCLES = "soak_cycles"
CONF_SOAK_PAUSE_MINUTES = "soak_pause_minutes"
DEFAULT_SOAK_CYCLES = 1
DEFAULT_SOAK_PAUSE_MINUTES = 30

CROP_COEFFICIENTS = {
    "lawn": 0.8,
    "mixed": 0.9,
    "garden": 1.0,
    "drip": 0.6,
}

SCAN_INTERVAL_MINUTES = 15
TREND_HOURS = 6
CALIBRATION_FOLLOWUP_SECONDS = 1800
STALE_SENSOR_HOURS = 8

ENTRY_TYPE_SYSTEM = "system"
ENTRY_TYPE_ZONE   = "zone"

HOUR_LABELS = [
    "12:00 AM", "1:00 AM",  "2:00 AM",  "3:00 AM",  "4:00 AM",  "5:00 AM",
    "6:00 AM",  "7:00 AM",  "8:00 AM",  "9:00 AM",  "10:00 AM", "11:00 AM",
    "12:00 PM", "1:00 PM",  "2:00 PM",  "3:00 PM",  "4:00 PM",  "5:00 PM",
    "6:00 PM",  "7:00 PM",  "8:00 PM",  "9:00 PM",  "10:00 PM", "11:00 PM",
]
